### PR TITLE
persistent data

### PR DESCRIPTION
**Pull request by Axilotl17**
now you can leave the page

### CODE REVIEW

**Comment by Axilotl17** [comment]
apparently this broke the shop somehow but idk how

**Comment by Axilotl17** [comment]
ive only fixed one, but ill fix the others now too

**Comment by Scraft161** [comment]
ok, for the time being this seems to work*, there are a few things I do want to note though.
1. I don't think saving every tick is going to be a smart move, right now the game does run at 1 tick/s; but I do want a way for tickspeed upgrades down the line which could stack up to the game doing thousands of ticks/s, I personally think creating another timer to save every x minute would be the smarter move (I'm thinking Antimatter Dimensions which saves every 3 minutes)
2. This is overhauling quite a bit if backend logic to stuff everything in an object with localstorage, this definitely isn't a bad thing but I do definitely want to see this in action for a bit before we put it as the main version (I have no doubt you've done this well, but better be safe than sorry)
3. Maybe we should give the user some heads up that we're storing things in the browser? not that they're going to go after a stupid game like this but I for sure don't want GDPR violations on my ass or anything like that, I don't know how we should go about this or if we should make it opt-out; but I do know most other idle games don't seem to care much at all and they've been fine so far.

for the time being I think it's best if we keep this in a feature branch somewhere and develop against that or put the pages site on a "stable" branch and develop against master.
I'd love to hear your feedback on all of this before we move forward.

**Comment by Scraft161** [comment]
Merging into persistent storage feature branch

**Pull request merged**
